name: Build Trial Master File Reference Model Transformations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-json:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.13.4"]
        otp: ["25.0.4"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Dependencies
        run: |
          mix local.hex --force

      - name: Run Transforms
        run: |
          elixir tmf-transform.exs

      - name: Set PRELEASE_SUFFIX
        run: |
          SHORT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | sed 's/.*\///g' | cut -c1-8)
          echo "::set-env name=PRERELEASE_SUFFIX::${SHORT_BRANCH_NAME}"

      - name: Bump version but don't push tag
        id: bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: synclinical
          DRY_RUN: true
          WITH_V: true
          # PRERELEASE_SUFFIX: #comes from the previous step step

      - name: Test Tag
        run: |
          echo ${{ steps.bump.outputs.new_tag.value }
          echo ${{ steps.bump.outputs.tag.value }
          echo ${{ steps.bump.outputs.part.value }
 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag.value }}
          draft: ${{ github.ref != 'refs/heads/main' }}
          files: |
            LICENSE
            *.json
