name: Build Trial Master File Reference Model Transformations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-json:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.13.4"]
        otp: ["25.0.4"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Dependencies
        run: |
          mix local.hex --force

      - name: Run Transforms
        run: |
          elixir tmf-transform.exs

      - name: Set PRELEASE_SUFFIX
        run: |
          SHORT_BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/.*\///g' | cut -c1-8)
          echo "prerelease_suffix=${SHORT_BRANCH_NAME}" >> $GITHUB_ENV

      - name: Bump version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          append_to_pre_release_tag: ${{ env.prerelease_suffix }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.tag_version.outputs.new_tag }}"
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: ${{ github.ref != 'refs/heads/main' }}
          files: |
            LICENSE
            *.json
